CREATE TABLE IF NOT EXISTS targets (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  longitude NUMERIC(10, 7) NOT NULL,
  latitude NUMERIC(10, 7) NOT NULL,
  owner_id INTEGER NOT NULL,
  end_time TIMESTAMP WITHOUT TIME ZONE NOT NULL
);