version: '3.8'

services:
  imagereceiver:
    build:
      context: ./imagereceiver
      dockerfile: /Dockerfile
    volumes:
      - ./imagereceiver:/app
      - ./data/images:/app/images
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://admin:password@postgres:5432/photoprestige
      - PORT=4000
  postgres:
    image: postgres:16
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: photoprestige